# Generated by Django 5.2.3 on 2025-07-15 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_type', models.CharField(choices=[('training', 'Тренувальна'), ('competition', 'Змагальна')], max_length=20)),
                ('place', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AttemptVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='attempt_videos/')),
                ('event_type', models.CharField(choices=[('jump', 'Стрибки'), ('throw', 'Штовхання/Метання'), ('run', 'Біг')], max_length=20)),
                ('result', models.CharField(help_text='Результат (м, с)', max_length=20)),
                ('attempt_number', models.PositiveIntegerField()),
                ('place', models.PositiveIntegerField()),
                ('time', models.TimeField(help_text='Час спроби')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='dashboard.attemptcategory')),
            ],
        ),
    ]
