# Generated by Django 5.2.3 on 2025-08-18 16:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_otpcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attemptcategory',
            options={'ordering': ['-date', 'place'], 'verbose_name': 'Категорія спроб', 'verbose_name_plural': 'Категорії спроб'},
        ),
        migrations.AlterModelOptions(
            name='attemptvideo',
            options={'ordering': ['-category__date', 'event_type', 'attempt_number'], 'verbose_name': 'Відео спроби', 'verbose_name_plural': 'Відео спроб'},
        ),
        migrations.AlterModelOptions(
            name='otpcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Одноразовий код', 'verbose_name_plural': 'Одноразові коди'},
        ),
        migrations.AddField(
            model_name='attemptvideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Створено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attemptvideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='attemptcategory',
            name='attempt_type',
            field=models.CharField(choices=[('training', 'Тренувальна'), ('competition', 'Змагальна')], db_index=True, max_length=20, verbose_name='Тип спроби'),
        ),
        migrations.AlterField(
            model_name='attemptcategory',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='attemptcategory',
            name='place',
            field=models.CharField(max_length=100, verbose_name='Місце проведення'),
        ),
        migrations.AlterField(
            model_name='attemptvideo',
            name='attempt_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер спроби'),
        ),
        migrations.AlterField(
            model_name='attemptvideo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='dashboard.attemptcategory', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='attemptvideo',
            name='event_type',
            field=models.CharField(choices=[('jump', 'Стрибки'), ('throw', 'Штовхання/Метання'), ('run', 'Біг')], db_index=True, max_length=20, verbose_name='Дисципліна'),
        ),
        migrations.AlterField(
            model_name='attemptvideo',
            name='place',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Місце в протоколі'),
        ),
        migrations.AlterField(
            model_name='attemptvideo',
            name='result',
            field=models.CharField(help_text='Результат (м або с)', max_length=20, verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='attemptvideo',
            name='time',
            field=models.TimeField(blank=True, help_text='Час спроби (необов’язково)', null=True, verbose_name='Час спроби'),
        ),
        migrations.AlterField(
            model_name='attemptvideo',
            name='video',
            field=models.FileField(upload_to='attempt_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'm4v', 'avi', 'mkv'])], verbose_name='Відео'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Код має складатися з 6 цифр.')], verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AddIndex(
            model_name='attemptvideo',
            index=models.Index(fields=['event_type'], name='dashboard_a_event_t_e34cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptvideo',
            index=models.Index(fields=['category', 'attempt_number'], name='dashboard_a_categor_19d5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['user', 'created_at'], name='dashboard_o_user_id_cf7d0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='otpcode',
            constraint=models.UniqueConstraint(fields=('user', 'code'), name='unique_user_otp_code'),
        ),
    ]
