# Generated by Django 5.2.3 on 2025-08-18 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_attemptcategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptVideoAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, verbose_name='Дані анотацій')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Оновлено користувачем')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annotation', to='dashboard.attemptvideo', verbose_name='Відео')),
            ],
            options={
                'verbose_name': 'Анотації відео',
                'verbose_name_plural': 'Анотації відео',
            },
        ),
    ]
