# Generated by Django 5.2.3 on 2025-08-24 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_attemptvideoannotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attemptvideo',
            name='place',
        ),
        migrations.AddField(
            model_name='attemptcategory',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Зайняте місце'),
        ),
        migrations.AddField(
            model_name='attemptvideo',
            name='place_in_protocol',
            field=models.PositiveIntegerField(blank=True, db_column='place', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Місце в протоколі'),
        ),
    ]
