# Generated by Django 5.2.3 on 2025-08-25 23:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_attemptvideo_place_attemptcategory_rank_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attemptcategory',
            options={'ordering': ['-date', 'place'], 'verbose_name': 'Attempt category', 'verbose_name_plural': 'Attempt categories'},
        ),
        migrations.AlterModelOptions(
            name='attemptvideo',
            options={'ordering': ['-category__date', 'event_type', 'attempt_number'], 'verbose_name': 'Attempt video', 'verbose_name_plural': 'Attempt videos'},
        ),
        migrations.AlterModelOptions(
            name='attemptvideoannotation',
            options={'verbose_name': 'Video annotations', 'verbose_name_plural': 'Video annotations'},
        ),
        migrations.AlterModelOptions(
            name='otpcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'One-time code', 'verbose_name_plural': 'One-time codes'},
        ),
        migrations.AlterField(
            model_name='attemptcategory',
            name='attempt_type',
            field=models.CharField(choices=[('training', 'Training'), ('competition', 'Competition')], db_index=True, max_length=20, verbose_name='Attempt type'),
        ),
        migrations.AlterField(
            model_name='attemptcategory',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='attemptcategory',
            name='place',
            field=models.CharField(max_length=100, verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='attemptcategory',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Rank in protocol'),
        ),
        migrations.AlterField(
            model_name='attemptvideo',
            name='attempt_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Attempt number'),
        ),
        migrations.AlterField(
            model_name='attemptvideo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='dashboard.attemptcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='attemptvideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='attemptvideo',
            name='event_type',
            field=models.CharField(choices=[('jump', 'Jumps'), ('throw', 'Throw/Shot put'), ('run', 'Run')], db_index=True, max_length=20, verbose_name='Discipline'),
        ),
        migrations.AlterField(
            model_name='attemptvideo',
            name='place_in_protocol',
            field=models.PositiveIntegerField(blank=True, db_column='place', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Place (protocol)'),
        ),
        migrations.AlterField(
            model_name='attemptvideo',
            name='result',
            field=models.CharField(help_text='Result (m or s)', max_length=20, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='attemptvideo',
            name='time',
            field=models.TimeField(blank=True, help_text='Attempt time (optional)', null=True, verbose_name='Attempt time'),
        ),
        migrations.AlterField(
            model_name='attemptvideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='attemptvideo',
            name='video',
            field=models.FileField(upload_to='attempt_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'm4v', 'avi', 'mkv'])], verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='attemptvideoannotation',
            name='data',
            field=models.JSONField(default=dict, verbose_name='Annotation data'),
        ),
        migrations.AlterField(
            model_name='attemptvideoannotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='attemptvideoannotation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='attemptvideoannotation',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annotation', to='dashboard.attemptvideo', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Code must contain 6 digits.')], verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
